version: '3.8'

services:
  web:
    build: .
    volumes:
      - ".:/app"
    working_dir: /app
    command: bash -c "bundle install && bundle exec rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
    # depends_on:
    #   - db
    networks:
      - myapp-network

  # No separate database service required for SQLite

# volumes:
  # Define volumes if needed for persistent storage

networks:
  myapp-network:
